services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_KEY=${APP_KEY:-your-app-key}
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge


